---
# Source: cloudbees-flow/charts/nginx-ingress/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.25.0
    heritage: Helm
    release: cloudbees-cd
  name: cloudbees-cd-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudbees-cd-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: cloudbees-cd-nginx-ingress
    namespace: cloudbees-cd
