---
# Source: cloudbees-flow/charts/nginx-ingress/templates/default-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.25.0
    component: "default-backend"
    heritage: Helm
    release: cloudbees-cd
  name: cloudbees-cd-nginx-ingress-default-backend
  namespace: cloudbees-cd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nginx-ingress
    component: "default-backend"
    release: cloudbees-cd
  type: "ClusterIP"
