---
# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  namespace: "secret-infra"
  annotations: 
    iam.gke.io/gcp-service-account: cbp-loving-gelding-sm@arc-poc-cbp-test-0902-2.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
