apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: cloudbees-cd
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: kubernetes-external-secrets