---
# Source: cloudbees-flow/charts/mariadb/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: "mariadb"
    component: "master"
    chart: "mariadb-7.0.1"
    release: "cloudbees-cd"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mariadb"
    component: "master"
    release: "cloudbees-cd"
