{{- if .Values.server.enabled -}}
{{ if not (or .Values.database.externalEndpoint .Values.database.clusterEndpoint) }}
{{ required "Either of .database.externalEndpoint or .database.clusterEndpoint has to be specified and available for Flow server to run" .dbEndpoint }}
{{ end }}
{{ if .Values.database.externalEndpoint  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudbees-flow-external-db
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ExternalName
  externalName: "{{ .Values.database.externalEndpoint }}"
  selector: {}
{{- end }}
{{- end }}
