{{- if and .Values.ingress.enabled (not (include "cloudbees-flow.is-openshift" .)) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: flow
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if or .Values.ingress.certificate.existingSecret .Values.ingress.certificate.crt  }}
{{- if .Values.ingress.host }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
{{- if .Values.ingress.certificate.existingSecret }}
      secretName: {{ .Values.ingress.certificate.existingSecret | quote }}
{{- else if and .Values.ingress.certificate.crt .Values.ingress.certificate.key }}
      secretName: "flow-tls-secret"
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.web.enabled }}
{{- if .Values.sda }}
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
        - path: /flow
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /flow/*
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /commander
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /commander/*
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /auth
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /auth/*
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /rest
          backend:
            service:
              name: flow-web
              port:
                number: 80
        - path: /rest/*
          backend:
            service:
              name: flow-web
              port:
                number: 80
{{- else}}
  defaultBackend:
    service:
      name: flow-web
      port:
        number: 80
{{- end }}
{{- end }}
{{- end }}


