{{- if and .Values.server.enabled  .Values.server.externalService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: flow-server-external
  labels:
    app: flow-server
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: servicep1-stomp
      port: 61613
      protocol: TCP
      targetPort: p1-stomp
    - name: servicep6jettys
      port: 8443
      protocol: TCP
      targetPort: p6-jettys
  selector:
    app: flow-server
    release: {{ .Release.Name }}
{{ end }}
