---
# Source: cloudbees-flow/templates/mariadb-initdb-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-scripts
  labels:
    app: cloudbees-flow
    chart: cloudbees-flow
data:
    demo-db.sql: |-
        CREATE DATABASE IF NOT EXISTS demo CHARACTER SET utf8 COLLATE utf8_unicode_ci;
        CREATE DATABASE IF NOT EXISTS demo_upgrade CHARACTER SET utf8 COLLATE utf8_unicode_ci;
        GRANT ALL PRIVILEGES ON demo.* TO 'flow'@'%';
        GRANT ALL PRIVILEGES ON demo_upgrade.* TO 'flow'@'%';
        FLUSH PRIVILEGES;
