---
# Source: cloudbees-flow/templates/mariadb-initdb-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-scripts
  namespace: cloudbees-cd
  labels:
    app: cloudbees-flow
    chart: cloudbees-flow
data:
    demo-db.sql: |-
        CREATE DATABASE IF NOT EXISTS commander CHARACTER SET utf8 COLLATE utf8_unicode_ci;
        CREATE DATABASE IF NOT EXISTS commander_upgrade CHARACTER SET utf8 COLLATE utf8_unicode_ci;
        GRANT ALL PRIVILEGES ON commander.* TO 'flow'@'%';
        GRANT ALL PRIVILEGES ON commander_upgrade.* TO 'flow'@'%';
        FLUSH PRIVILEGES;
