---
# Source: cloudbees-flow/templates/repository-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-repository
  namespace: cloudbees-cd
  labels:
    app: flow-repository
    chart: cloudbees-flow
    release: cloudbees-cd
    heritage: Helm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: flow-repository
      release: cloudbees-cd
  template:
    metadata:
      labels:
        app: flow-repository
        release: cloudbees-cd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: default
      initContainers:
        - name: volumes-permissions
          image: "docker.io/cloudbees/cbflow-repository:10.2.0.148735_2.1.22_20210527"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: repository-data-volume
            mountPath: /repository-data
          command:
          - sh
          - -c
          - |
            set -e
            set -x
            chown -R 1000:1000 /repository-data
          resources:
            limits:
              cpu: "25m"
              memory: "128Mi"
            requests:
              cpu: "25m"
              memory: "128Mi"
      containers:
        - name: flow-repository
          image: "docker.io/cloudbees/cbflow-repository:10.2.0.148735_2.1.22_20210527"
          imagePullPolicy: IfNotPresent
          env:
          - name: CBF_REPOSITORY_NAME
            value: "default"
          - name: PUBLIC_HOSTNAME
            value: "flow-repository"
          - name: CBF_SERVER_HOST
            value: "flow-server"
          - name: CBF_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudbees-cd-password
                key: CBF_SERVER_ADMIN_PASSWORD
          - name: CBF_SERVER_USER
            value: admin
          - name: CBF_LOCAL_RESOURCE_HOST
            value: flow-bound-agent
          - name: CBF_CONFIGURE
            value: --repositoryInitMemoryMB=256 --repositoryMaxMemoryMB=512
          ports:
          - containerPort: 8200
            name: p3-repository
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8200
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["/opt/cbflow/health-check"]
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "0.25"
              memory: 1024Mi
            requests:
              cpu: "0.25"
              memory: 512Mi
          volumeMounts:
          - name: repository-data-volume
            mountPath: /repository-data
          - name: logback-config
            mountPath: /custom-config/repository/logback-local.groovy
            subPath: repository-logback-config
      volumes:
      - name: repository-data-volume
        persistentVolumeClaim:
           claimName: flow-repo-artifacts
      - name: logback-config
        configMap:
          name: flow-logging-config
