---
# Source: cloudbees-flow/templates/server-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudbees-cd-cloudbees-flow-db
  labels:
    app: flow-server-db-secret
    chart: cloudbees-flow
type: Opaque
data:
  DB_PASSWORD:  WGtrUldpQVVYUHZBSG5SZHNYZHY=
  DB_USER: "Zmxvdw=="
---
# Source: cloudbees-flow/templates/server-secrets.yaml
# Copied from Mariadb Chart
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-initdb-secret
  labels:
    app: mariadb
    role: mariadb
type: Opaque
data:
  mariadb-root-password: a1BMbFJWa2t0V1NlQVZabnBtWlQ=
  mariadb-password: "WGtrUldpQVVYUHZBSG5SZHNYZHY="
---
# Source: cloudbees-flow/templates/server-secrets.yaml
---
