---
# Source: cloudbees-flow/templates/server-secrets.yaml
# Copied from Mariadb Chart
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-initdb-secret
  labels:
    app: mariadb
    role: mariadb
type: Opaque
data:
  mariadb-root-password: bmx3d2NkRmhvUktjc0hNVENLWlQ=
  mariadb-password: "QmpmVXBYWFNyck1RZVV3eVR1d3c="
---
# Source: cloudbees-flow/templates/server-secrets.yaml
---
