---
# Source: cloudbees-flow/templates/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-web
  namespace: cloudbees-cd
  labels:
    app: flow-web
    chart: cloudbees-flow
    release: cloudbees-cd
    heritage: Helm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: flow-web
      release: cloudbees-cd
  template:
    metadata:
      labels:
        app: flow-web
        release: cloudbees-cd
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: flow-server
      serviceAccountName: default
      containers:
        - name: flow-web
          image: "docker.io/cloudbees/cbflow-web:build-10.3.0.150739_3.0.24_20210910"
          imagePullPolicy: IfNotPresent
          env:
          - name: CBF_WEB_HOST
            value: flow-web
          - name: CBF_SERVER_HOST
            value: "flow-server"
          - name: CBF_LOCAL_RESOURCE_HOST
            value: flow-bound-agent
          - name: CBF_WEB_NO_HTTPS_REDIRECT
            value: "1"
          readinessProbe:
            tcpSocket:
              port: 2080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["/opt/cbflow/health-check"]
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          ports:
          - name: http
            containerPort: 2080
            protocol: TCP
          - name: https
            containerPort: 2443
            protocol: TCP
          volumeMounts:
          - name: plugins-volume
            mountPath: "/plugins-data"
      volumes:
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: "flow-server-shared"
