apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgen-ui
  namespace: cloudbees-cd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nextgen-ui
  template:
    metadata:
      labels:
        app: nextgen-ui
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/fleet-cbp-poc/container-images/nextgen-ui:0.1.5
          name: nextgen-ui
          ports:
            - containerPort: 80
