---
# Source: cloudbees-flow/templates/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nextgen-ui
  namespace: cloudbees-cd
  labels:
    app: nextgen-ui
spec:
  type: ClusterIP
  ports:
    - name: httpefwebserver
      port: 80
      protocol: TCP
      targetPort: 80
    - name: httpsefwebserver
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nextgen-ui