# Default values for cloudbees-flow-agent chart
#
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  registry: "docker.io/cloudbees"
  imageRepository: "cbflow-agent"
  tag: "10.2.1.150122_3.0_20210802"
  pullPolicy: IfNotPresent

  # Image pull secrets
  # Enable this option when using a private registry.
  # Secrets must be manually created in the namespace.
  # imagePullSecrets: <secret-name>

  # Optional array of imagePullSecrets containing private registry credentials
  # Reference to one or more secrets to be used when pulling images
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # imagePullSecrets:
  # - name: "docker-registry"

  imagePullSecrets:

# Please state flow-server endpoint here. Please note that if installing in different namespace than server
# service name has to be stated in form "service-name.namespace"
# Here we assume the same namespace
serverEndpoint: flow-server

#---------------------------------------------
# Flow agent configuration section
#---------------------------------------------

# List of resource pools agents will try to register with upon coming up and registering with server
resourcePools:

# Flow resource name which agents of this deployment will be assigned to (defaults to hostname)
#
# Ordinary helm template values are allowed here. For example: {{ .Release.Name }},
# {{ .Release.Namespace }} etc. Also, 2 special templates are allowed here:
#
#     {{ hostname }} - will be replaced by the actual resource hostname
#     {{ ordinalIndex }} - will be replaced by a serial replica index in StatefulSet
#
# Sample:
#
#     resourceName: "myResource - {{ .Release.Name }} - {{ ordinalIndex }}"
#
resourceName:

# Release name prefix added to support this chart to launch as multiple subchart in CD deployment
# keep this empty for standalone deployments
releaseNamePrefix:

# Number of replicas
replicas: 1

# The default is to deploy all pods serially. By setting this to parallel 
# all pods are started at the same time.
podManagementPolicy: "Parallel"

# The zone (must exist in CloudBees Flow server instance) for
# the resources created in the Flow server for the agent(s).
zoneName:

# The default workspace (must exist in CloudBees Flow server instance) for
# the resources created in the Flow server for the agent(s).
workspaceName:

# Set to true to configure the agent as a trusted agent,
# restricting the agent to one CloudBees Flow server deployment
trustedAgent: false

# Type of resource to create on the remote CloudBees
# Flow server. This argument is relevant only when the
# CloudBees Flow server is using a mixed-mode license
# (concurrent resources and registered hosts).
# Valid options for this argument are 'concurrent'
# or 'registered'.
resourceType:

#---------------------------------------------
# Pod scheduling settings
#---------------------------------------------

nodeSelector: {}
tolerations: []
affinity: {}


# This line is interpreted as if passsed to ecconfigure utility within the container
ecconfigure: "--agentInitMemoryMB=16 --agentMaxMemoryMB=64"

# Master loglevel for com.electriccloud package
logLevel: DEBUG


service:
  type: ClusterIP
  clusterIP: "None"
# External DNS hostname to set to as agent service name. For Gateway Agent configuration.
  publicHostName: null

#---------------------------------------------
# Flow agent storage and resources configuration section
#---------------------------------------------

# Agent workspace volume related settings: volume-name,
# access-mode (either nfs(aka ReadWriteMany) or thrditional volume mount(aka ReadWriteOnce))
# and storage amount
storage:
  volumes:
    agentWorkspace:
      name: flow-agent-workspace
      accessMode: ReadWriteOnce
      storage: 5Gi
# In order to use any non "platform-default" or custom storage class just uncomment the line and and state required storageClass name
#     storageClass: my-class
#
# If defined true if any agent is already deployed with shared workspace and pvc already exist
      existingClaim: false


resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 0.25
    memory: 512Mi

#---------------------------------------------
# Flow server credentials configuration section
#---------------------------------------------

# Flow server credentials to use in order to register with agent as a resource on the Flow server.
# 'admin' user is used by default. You may user a different user if desired. The user must have
# `modify` permissions on `resources` on the Flow server.
# serverSecretReference is added to support case where agents need to refer  flow servers existing admin credentials
flowCredentials:
  existingSecret:
  serverSecretReference: false
  user: admin
  password:



#---------------------------------------------
# Pods security context
#---------------------------------------------

securityContext:
  enabled: false
  fsGroup: 1000
  runAsUser: 1000

rbac:
  ## Specifies whether RBAC resources should be created
  ##
  create: false
  serviceAccountName:
  role:
    ## Rules to create.
    rules: []


volumePermissions:
  enabled: true

podSecurityPolicy:
  create: false
  annotations: {}
    ## Specify pod annotations
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
    ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#sysctl
    ##
    # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
    # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'


gateway:
  # install this agent as gateway agent
  enabled: false
  # Name of the gateway to create
  name: external
  # Name of gateway agent to pair with as gateway resource 2
  pairedResourceName: gateway-default-agent


