apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/fleet-cbp-poc/container-images/example-app:0.0.1
          name: example-app
          ports:
            - containerPort: 3000
