{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cbflowagent-role-{{ .Values.releaseNamePrefix | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: cbflowagent-role-{{ .Values.releaseNamePrefix | default .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - cbflowagent-psp-{{ .Values.releaseNamePrefix | default .Release.Name  }}
{{- end -}}
{{- if .Values.rbac.role.rules }}
{{ toYaml .Values.rbac.role.rules | indent 2 }}
{{- end -}}
{{- end -}}
