{{- if include "serviceAccount.enabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudbees-flow-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloudbees-flow-agent.serviceAccountName" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.images.imagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.images.imagePullSecrets }}
- name: {{ .Values.images.imagePullSecrets }}
{{- else }}
{{ toYaml .Values.images.imagePullSecrets }}
{{- end -}}
{{- end -}}
{{- end -}}