apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agents"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agent-service"
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: p2
      port: 7800
      protocol: TCP
      targetPort: p4-agent
  selector:
    app: "{{  .Values.releaseNamePrefix | default .Release.Name }}-flow-agent"
    release: {{ .Release.Name }}
