---
# Source: cloudbees-flow/charts/nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.25.0
    component: "controller"
    heritage: Helm
    release: cloudbees-cd
  name: cloudbees-cd-nginx-ingress-controller
  namespace: cloudbees-cd
data:
  proxy-stream-timeout: 4000s
