---
# Source: cloudbees-flow/charts/nginx-ingress/templates/tcp-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.25.0
    component: "controller"
    heritage: Helm
    release: cloudbees-cd
  name: cloudbees-cd-nginx-ingress-tcp
  namespace: cloudbees-cd
data:
  "8200": 'cloudbees-cd/flow-repository:8200'
  "8443": 'cloudbees-cd/flow-server:8443'
  "61613": 'cloudbees-cd/flow-server:61613'
