apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-password
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  data:
    - key: cloudbees-cd-password
      name: CBF_SERVER_ADMIN_PASSWORD # key name in the k8s secret
      property: CBF_SERVER_ADMIN_PASSWORD # name of the field in the GCP secret
      version: latest # version of the GCP secret
