apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-agent-credentials
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  data:
    - key: cloudbees-cd-agent-credentials
      name: CBF_SERVER_PASSWORD # key name in the k8s secret
      property: CBF_SERVER_PASSWORD # name of the field in the GCP secret
      version: latest # version of the GCP secret
    - key: cloudbees-cd-agent-credentials
      name: CBF_SERVER_USER # key name in the k8s secret
      property: CBF_SERVER_USER # name of the field in the GCP secret
      version: latest # version of the GCP secret
