apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-dois
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  data:
    - key: cloudbees-cd-dois
      name: CBF_DOIS_ADMIN_PASSWORD # key name in the k8s secret
      property: CBF_DOIS_ADMIN_PASSWORD # name of the field in the GCP secret
      version: latest # version of the GCP secret
    - key: cloudbees-cd-dois
      name: CBF_DOIS_PASSWORD # key name in the k8s secret
      property: CBF_DOIS_PASSWORD # name of the field in the GCP secret
      version: latest # version of the GCP secret
