apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-db
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  data:
    - key: cloudbees-cd-db
      name: DB_USER # key name in the k8s secret
      property: DB_USER # name of the field in the GCP secret
      version: latest # version of the GCP secret
    - key: cloudbees-cd-db
      name: DB_PASSWORD # key name in the k8s secret
      property: DB_PASSWORD # name of the field in the GCP secret
      version: latest # version of the GCP secret
