apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-mariadb
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  data:
    - key: cloudbees-cd-mariadb
      name: mariadb-root-password # key name in the k8s secret
      property: mariadb-root-password # name of the field in the GCP secret
      version: latest # version of the GCP secret
    - key: cloudbees-cd-mariadb
      name: mariadb-password # key name in the k8s secret
      property: mariadb-password # name of the field in the GCP secret
      version: latest # version of the GCP secret
    - key: cloudbees-cd-mariadb
      name: mariadb-replication-password # key name in the k8s secret
      property: mariadb-replication-password # name of the field in the GCP secret
      version: latest # version of the GCP secret
