apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudbees-cd-license
  namespace: cloudbees-cd
spec:
  backendType: gcpSecretsManager
  projectId: fleet-cbp-poc
  data:
    - key: cloudbees-cd-license
      name: CBF_LICENSE # key name in the k8s secret
      property: CBF_LICENSE # name of the field in the GCP secret
      version: latest # version of the GCP secret
