
serviceAccount:
  name: kubernetes-external-secrets
  annotations:
    iam.gke.io/gcp-service-account: cb-platform-sm@arc-poc-cbp-test-0902-2.iam.gserviceaccount.com

fullname: kubernetes-external-secrets
fullnameOverride: kubernetes-external-secrets