annotations:
  artifacthub.io/links: |
    - name: Product overview
      url: https://www.cloudbees.com/products/continuous-delivery
    - name: Documentation
      url: https://docs.cloudbees.com/docs/cloudbees-cd/latest/
apiVersion: v2
appVersion: 10.2.1.150122
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.helm.sh/stable
  version: 7.0.1
- condition: clusteredMode
  name: zookeeper
  repository: https://charts.helm.sh/incubator
  version: 2.1.1
- condition: nginx-ingress.enabled
  name: nginx-ingress
  repository: https://charts.helm.sh/stable
  version: 1.25.0
- alias: externalGatewayAgent
  condition: externalGatewayAgent.enabled
  name: cloudbees-flow-agent
  repository: ""
  version: "2"
- alias: internalGatewayAgent
  condition: internalGatewayAgent.enabled
  name: cloudbees-flow-agent
  repository: ""
  version: "2"
description: A Helm chart for CloudBees Flow
home: https://www.cloudbees.com/products/continuous-delivery
keywords:
- cloudbees-flow
- cloudbees-cd
name: cloudbees-flow
type: application
version: 2.10.2
